Repository NewSpring/corinth, pull requests merged in 2020-04, with the labels that each got.

#113 chore: Uses Yarn for Tests
  .github/workflows/tests.yml
Labels: merge

#111 fix: Better Loading States
  src/ui/HorizontalContentSeriesFeedConnected.js
Labels: merge, ready for review

#81 perf: Paginated Prayers
  .mergify.yml
  ios/Podfile.lock
  src/prayer/AddPrayer/AddPrayerForm/AddPrayerFormConnected.js
  src/prayer/PrayerList/index.js
  src/prayer/PrayerSingle/index.js
  src/prayer/PrayerTabView/PrayerTab.js
  src/prayer/PrayerTabView/index.js
  src/prayer/SaveButton/SaveButton.js
  src/prayer/SaveButton/SaveButton.tests.js
  src/prayer/SaveButton/__snapshots__/SaveButton.tests.js.snap
  src/prayer/SaveButton/index.js
  src/prayer/UserPrayerList/UserPrayerList.tests.js
  src/prayer/UserPrayerList/__snapshots__/UserPrayerList.tests.js.snap
  src/prayer/UserPrayerList/index.js
  src/prayer/data/fragments/prayerFragment.js
  src/prayer/data/mutations/savePrayer.js
  src/prayer/data/mutations/unSavePrayer.js
  src/prayer/data/queries/getPrayerCount.js
  src/prayer/data/queries/getPrayerFeed.js
  src/prayer/data/queries/getPrayerSaveState.js
  src/prayer/data/queries/getPrayers.js
  src/prayer/data/updates/flagPrayerUpdateAll.js
  src/ui/Locations/index.js
Labels: blocked, merge

#121 chore: Update Schema
  schema.graphql
Labels: merge, ready for review

#130 fix: Adds Pills Back to Universal Content Items
  loadConfig.js
  schema.graphql
  src/client/fragmentTypes.json
Labels: merge, ready for review

#99 chore: Removes Custom UI Elements
  package.json
  src/content-feed/__snapshots__/content-feed.tests.js.snap
  src/content-feed/index.js
  src/content-single/WeekendContentItem/index.js
  src/tabs/connect/Connect.js
  src/tabs/connect/index.js
  src/tabs/discover/SearchFeed/__snapshots__/SearchFeed.tests.js.snap
  src/tabs/discover/SearchFeed/getSearchResults.js
  src/tabs/discover/SearchFeed/index.js
  src/tabs/discover/__snapshots__/discover.tests.js.snap
  src/tabs/home/Home.js
  src/tabs/home/__snapshots__/home.tests.js.snap
  src/ui/BrandedCard.js
  src/ui/HorizontalLikedContentFeed.js
  src/ui/HorizontalLikedContentFeedConnected.js
  src/ui/LikedContentFeedConnected.js
  src/ui/LiveIcon.js
  src/ui/SearchInputHeader/__snapshots__/SearchInputHeader.tests.js.snap
  yarn.lock
Labels: merge

#137 fix: Discover feed works again on Android
  package.json
  schema.graphql
  src/tabs/discover/__snapshots__/discover.tests.js.snap
  src/ui/SearchInputHeader/__snapshots__/SearchInputHeader.tests.js.snap
  yarn.lock
Labels: merge, ready for review
