Repository NewSpring/corinth, pull requests merged in 2020-02, with the labels that each got.

#43 Beta Release
  .travis.yml
  CHANGELOG.md
  package.json
  src/index.js
  yarn.lock
Labels: ready for review

#45 7.5.16 Production Release
  .env.production
  .travis.yml
  CHANGELOG.md
  __mocks__/react-native-permissions/index.js
  android/app/build.gradle
  android/app/src/main/assets/appcenter-config.json
  android/app/src/main/res/values/strings.xml
  apollos.json
  appcenter-post-clone.sh
  ios/AppCenter-Config.plist
  ios/Podfile
  ios/Podfile.lock
  ios/newspringchurchapp-tvOS/Info.plist
  ios/newspringchurchapp-tvOSTests/Info.plist
  ios/newspringchurchapp.xcodeproj/project.pbxproj
  ios/newspringchurchapp/AppDelegate.m
  ios/newspringchurchapp/Info.plist
  ios/newspringchurchappTests/Info.plist
  package.json
  schema.graphql
  scripts/bump-version-code.sh
  src/NavigationService.js
  src/bugsnag.js
  src/client/index.js
  src/content-single/HTMLContent/index.js
  src/index.js
  src/prayer/data/queries/getCampusPrayers.js
  src/prayer/data/queries/getGroupPrayers.js
  src/prayer/data/queries/getPrayers.js
  src/tabs/connect/Connect.js
  src/tabs/connect/RecentlyLikedTileFeed/RecentlyLikedTileFeed.js
  src/tabs/connect/getUserProfile.js
  src/tabs/discover/DiscoverFeed/TileContentFeed.js
  src/tabs/home/Home.js
  src/ui/BrandedCard.js
  src/user-settings/Locations/Marker.js
  src/user-settings/getUserPhoto.js
  src/user-settings/index.js
  src/user-settings/uploadPhoto.js
  yarn.lock
Labels: ready for review

#42 chore: Fixes feed cards
  src/tabs/discover/DiscoverFeed/TileContentFeed.js
  src/tabs/discover/SearchFeed/SearchFeed.tests.js
  src/tabs/discover/SearchFeed/__snapshots__/SearchFeed.tests.js.snap
  src/tabs/discover/SearchFeed/getSearchResults.js
  src/tabs/discover/SearchFeed/index.js
  src/tabs/home/Home.js
Labels: ready for review

#47 chore: Additional 1.3.0 UI Fixes
  loadConfig.js
  src/content-feed/__snapshots__/content-feed.tests.js.snap
  src/content-feed/index.js
  src/content-single/HorizontalContentFeed/index.js
  src/prayer/PrayerTabView/PrayerTab.js
  src/tabs/connect/Connect.js
  src/tabs/discover/DiscoverFeed/TileContentFeed.js
  src/ui/HorizontalLikedContentFeed.js
  src/ui/HorizontalLikedContentFeedConnected.js
Labels: merge, ready for review

#51 fix: Fixes Videos...Again
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: merge

#52 fix: Fix the liked content feed
  src/tabs/connect/index.js
  src/ui/LikedContentFeedConnected.js
Labels: merge, ready for review

#44 chore: Fixes Live Click Tracking
  src/content-single/MediaControls/index.js
  src/tabs/home/Features/index.js
  src/ui/LiveButton.js
Labels: merge

#53 fix: Fixes the UI on the campaign card when we're live
  src/tabs/home/Home.js
Labels: merge, ready for review

#49 fix: Fixes Campaign Loading State
  src/tabs/discover/SearchFeed/__snapshots__/SearchFeed.tests.js.snap
  src/ui/BrandedCard.js
Labels: merge

#48 fix: Fixes Android Icon
  android/app/src/main/ic_launcher-web.png
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/app/src/main/res/values/ic_launcher_background.xml
Labels: merge

#46 chore: Adds Auto-versioning
  .travis.yml
  package.json
Labels: merge

#23 chore: Updates to use new prayer queries
  src/prayer/AddPrayer/AddPrayerForm/AddPrayerFormConnected.js
  src/prayer/PrayerTabView/index.js
  src/prayer/SaveButton/index.js
  src/prayer/UserPrayerList/UserPrayerList.tests.js
  src/prayer/UserPrayerList/index.js
  src/prayer/data/queries/getCampusPrayers.js
  src/prayer/data/queries/getGroupPrayers.js
  src/prayer/data/queries/getPrayers.js
  src/prayer/data/queries/getSavedPrayers.js
  src/prayer/data/queries/getUserPrayers.js
  src/prayer/data/updates/flagPrayerUpdateAll.js
  src/user-settings/Locations/index.js
Labels: merge

#54 fix: Fixes Group Leader Link
  src/tabs/connect/getUserProfile.js
Labels: merge

#62 fix: Fixed the horizontal liked content feed card images
  src/ui/HorizontalLikedContentFeed.js
Labels: merge, ready for review

#57 chore: Paginated User Prayers
  schema.graphql
  src/prayer/PrayerSingle/index.js
  src/prayer/UserPrayerList/UserPrayerList.tests.js
  src/prayer/UserPrayerList/__snapshots__/UserPrayerList.tests.js.snap
  src/prayer/UserPrayerList/index.js
  src/prayer/data/queries/getPrayerFeed.js
Labels: ready for review

#64 chore: Updates Local Schema
  schema.graphql
Labels: merge

#59 chore: Adds Sermon Notes Analytics
  src/content-single/Features/NoteFeature.js
  src/content-single/Features/SermonNotes/index.js
  src/content-single/Features/TextFeature.js
Labels: merge

#63 chore: Attaches User to Bugsnag
  src/bugsnag.js
  src/client/index.js
Labels: merge

#68 chore: Adds Bad image info
  schema.graphql
  src/content-single/HTMLContent/index.js
Labels: merge

#67 chore: Fixes auto-versioning
  .travis.yml
  package.json
  scripts/bump-version-code.sh
Labels: merge

#70 Beta Release
  .travis.yml
  android/app/src/main/ic_launcher-web.png
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/app/src/main/res/values/ic_launcher_background.xml
  package.json
  schema.graphql
  scripts/bump-version-code.sh
  src/bugsnag.js
  src/client/index.js
  src/content-single/Features/NoteFeature.js
  src/content-single/Features/SermonNotes/index.js
  src/content-single/Features/TextFeature.js
  src/content-single/HTMLContent/index.js
  src/content-single/MediaControls/index.js
  src/prayer/AddPrayer/AddPrayerForm/AddPrayerFormConnected.js
  src/prayer/PrayerTabView/index.js
  src/prayer/SaveButton/index.js
  src/prayer/UserPrayerList/UserPrayerList.tests.js
  src/prayer/UserPrayerList/index.js
  src/prayer/data/queries/getCampusPrayers.js
  src/prayer/data/queries/getGroupPrayers.js
  src/prayer/data/queries/getPrayers.js
  src/prayer/data/queries/getSavedPrayers.js
  src/prayer/data/queries/getUserPrayers.js
  src/prayer/data/updates/flagPrayerUpdateAll.js
  src/tabs/connect/getUserProfile.js
  src/tabs/discover/SearchFeed/__snapshots__/SearchFeed.tests.js.snap
  src/tabs/home/Features/index.js
  src/tabs/home/Home.js
  src/ui/BrandedCard.js
  src/ui/HorizontalLikedContentFeed.js
  src/ui/LiveButton.js
  src/user-settings/Locations/index.js
Labels: merge

#66 chore: Updated the client to core version 1.3.0-beta.6
  apollos.json
  ios/Podfile.lock
  jest.setup.js
  package.json
  polyfill.js
  src/NavigationService.js
  src/content-single/ContentSeriesContentItem/index.js
  src/content-single/DevotionalContentItem/ContentTab.js
  src/content-single/DevotionalContentItem/Devotional.tests.js
  src/content-single/DevotionalContentItem/ScriptureTab.js
  src/content-single/DevotionalContentItem/index.js
  src/content-single/HorizontalContentFeed/getHorizontalContent.js
  src/content-single/MediaControls/getContentMedia.js
  src/content-single/UniversalContentItem/index.js
  src/content-single/WeekendContentItem/index.js
  src/index.js
  src/prayer/AddPrayer/AddPrayerForm/AddPrayerFormConnected.js
  src/prayer/AddPrayer/AddPrayerForm/AddPrayerFormConnected.tests.js
  src/tabs/connect/Connect.js
  src/tabs/connect/UserAvatarHeader.js
  src/tabs/connect/UserAvatarHeader/UserAvatarHeader.js
  src/tabs/connect/UserAvatarHeader/getUserProfile.js
  src/tabs/connect/UserAvatarHeader/index.js
  src/testing-control-panel/index.js
  src/ui/ContentHTMLViewConnected.js
  src/ui/HorizontalContentSeriesFeedConnected.js
  src/ui/Locations/Locations.test.js
  src/ui/Locations/MapView.js
  src/ui/Locations/Marker.js
  src/ui/Locations/__snapshots__/Locations.test.js.snap
  src/ui/Locations/campusChange.js
  src/ui/Locations/getCampusLocations.js
  src/ui/Locations/index.js
  src/ui/MediaControls.js
  src/ui/Onboarding/index.js
  src/ui/SearchCard/SearchCard.tests.js
  src/ui/SearchCard/__snapshots__/SearchCard.tests.js.snap
  src/ui/SearchCard/index.js
  src/ui/getContentItemContent.js
  src/user-settings/ChangeAvatar.js
  src/user-settings/PersonDetails.tests.js
  src/user-settings/PersonalDetails.js
  src/user-settings/getUserPhoto.js
  src/user-settings/index.js
  src/user-settings/uploadPhoto.js
  yarn.lock
Labels: merge, ready for review

#71 fix: Browser opens external links correctly
  package.json
  yarn.lock
Labels: ready for review

#69 fix: Fixes Links from mass emails
  src/linking/Provider.js
Labels: merge

#72 Beta Release
  apollos.json
  ios/Podfile.lock
  jest.setup.js
  package.json
  polyfill.js
  src/NavigationService.js
  src/content-single/ContentSeriesContentItem/index.js
  src/content-single/DevotionalContentItem/ContentTab.js
  src/content-single/DevotionalContentItem/Devotional.tests.js
  src/content-single/DevotionalContentItem/ScriptureTab.js
  src/content-single/DevotionalContentItem/index.js
  src/content-single/HorizontalContentFeed/getHorizontalContent.js
  src/content-single/MediaControls/getContentMedia.js
  src/content-single/UniversalContentItem/index.js
  src/content-single/WeekendContentItem/index.js
  src/index.js
  src/linking/Provider.js
  src/prayer/AddPrayer/AddPrayerForm/AddPrayerFormConnected.js
  src/prayer/AddPrayer/AddPrayerForm/AddPrayerFormConnected.tests.js
  src/tabs/connect/Connect.js
  src/tabs/connect/UserAvatarHeader.js
  src/tabs/connect/UserAvatarHeader/UserAvatarHeader.js
  src/tabs/connect/UserAvatarHeader/getUserProfile.js
  src/tabs/connect/UserAvatarHeader/index.js
  src/testing-control-panel/index.js
  src/ui/ContentHTMLViewConnected.js
  src/ui/HorizontalContentSeriesFeedConnected.js
  src/ui/Locations/Locations.test.js
  src/ui/Locations/MapView.js
  src/ui/Locations/Marker.js
  src/ui/Locations/__snapshots__/Locations.test.js.snap
  src/ui/Locations/campusChange.js
  src/ui/Locations/getCampusLocations.js
  src/ui/Locations/index.js
  src/ui/MediaControls.js
  src/ui/Onboarding/index.js
  src/ui/SearchCard/SearchCard.tests.js
  src/ui/SearchCard/__snapshots__/SearchCard.tests.js.snap
  src/ui/SearchCard/index.js
  src/ui/getContentItemContent.js
  src/user-settings/ChangeAvatar.js
  src/user-settings/PersonDetails.tests.js
  src/user-settings/PersonalDetails.js
  src/user-settings/getUserPhoto.js
  src/user-settings/index.js
  src/user-settings/uploadPhoto.js
  yarn.lock
Labels: ready for review
