Repository NewSpring/corinth, pull requests merged in 2020-03, with the labels that each got.

#78 fix: Removed series tag from content without children
  src/ui/HorizontalContentSeriesFeedConnected.js
Labels: merge, ready for review

#56 perf: Adds Prayer Pagination
  .mergify.yml
  schema.graphql
  src/prayer/AddPrayer/AddPrayerForm/AddPrayerFormConnected.js
  src/prayer/PrayerList/index.js
  src/prayer/PrayerTabView/PrayerTab.js
  src/prayer/PrayerTabView/index.js
  src/prayer/SaveButton/index.js
  src/prayer/UserPrayerList/index.js
  src/prayer/data/fragments/prayerFragment.js
  src/prayer/data/queries/getPrayerCount.js
  src/prayer/data/queries/getPrayerFeed.js
  src/prayer/data/queries/getPrayers.js
  src/prayer/data/updates/flagPrayerUpdateAll.js
  src/user-settings/Locations/index.js
Labels: merge

#74 chore: Adds scaffold for detox integration testing
  .eslintrc.js
  e2e/config.json
  e2e/firstTest.spec.js
  e2e/init.js
  package.json
  yarn.lock
Labels: merge

#88 chore: Removes Travis and Other Multi-branch Steps
  .travis.yml
  package.json
  scripts/bump-version-code.sh
  scripts/generate-icons.js
Labels: merge

#80 fix: Fixes scroll bar overlapping prayer
  src/prayer/PrayerSingle/__snapshots__/PrayerSingle.tests.js.snap
  src/prayer/PrayerSingle/index.js
Labels: merge

#89 chore: Remove Bugsnag Stage
  src/bugsnag.js
Labels: merge

#91 chore: Updates Mergify to Master Branch
  .mergify.yml
Labels: merge

#85 chore: Disables Bitcode
  ios/newspringchurchapp.xcodeproj/project.pbxproj
Labels: merge

#96 fix: Fix prayer top and bottom margins
  src/prayer/PrayerSingle/__snapshots__/PrayerSingle.tests.js.snap
  src/prayer/PrayerSingle/index.js
Labels: merge, ready for review

#94 chore: Added Instructions to Readme
  README.md
Labels: merge

#95 chore: Moved Appcenter Analytics
  src/Providers.js
  src/analytics/index.js
  src/content-single/Features/NoteFeature.js
  src/content-single/Features/SermonNotes/index.js
  src/content-single/Features/TextFeature.js
  src/index.js
  src/ui/LiveButton.js
  src/ui/MediaControls.js
Labels: merge

#97 chore: Update README.md
  README.md
Labels: merge

#100 chore: Better Links
  src/content-single/DevotionalContentItem/__snapshots__/Devotional.tests.js.snap
  src/prayer/AddPrayer/WithYou/__snapshots__/WithYou.tests.js.snap
  src/tabs/discover/DiscoverFeed/__snapshots__/DiscoverFeed.tests.js.snap
  src/tabs/discover/__snapshots__/discover.tests.js.snap
  src/theme/theme.js
  src/ui/Onboarding/__snapshots__/Onboarding.tests.js.snap
Labels: ready for review

#102 chore: Updates Schema
  schema.graphql
Labels: merge

#87 chore: Upgrades to Apollos 1.3.0
  .gitignore
  apollos.json
  ios/Podfile.lock
  package.json
  scripts/link-packages.js
  src/content-single/WeekendContentItem/index.js
  src/testing-control-panel/index.js
  src/theme/propOverrides.js
  src/theme/styleOverrides.js
  src/theme/theme.js
  src/user-web-browser/__tests__/__snapshots__/BrowserWithUserCookie.tests.js.snap
  yarn.lock
Labels: merge

#101 chore: Removed Force Exit From Tests
  .travis.yml
  package.json
Labels: merge

#103 chore: Live Button Plays in Native Player
  src/ui/LiveButton.js
Labels: merge, ready for review

#93 chore: Enable Github Actions
  .github/workflows/tests.yml
  .nvmrc
  .travis.yml
  package.json
Labels: merge
