Repository NewSpring/corinth, pull requests merged in 2020-01, with the labels that each got.

#12 fix: Fixes Videos on iOS
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: merge

#13 chore: Capitalized Bulleted List Items in Onboarding Process
  src/ui/Onboarding/__snapshots__/Onboarding.tests.js.snap
  src/ui/Onboarding/index.js
Labels: merge

#10 7.5.14
  CHANGELOG.md
  android/app/build.gradle
  appcenter-post-clone.sh
  ios/Podfile.lock
  ios/newspringchurchapp-tvOS/Info.plist
  ios/newspringchurchapp-tvOSTests/Info.plist
  ios/newspringchurchapp.xcodeproj/project.pbxproj
  ios/newspringchurchapp/Info.plist
  ios/newspringchurchappTests/Info.plist
  package.json
  scripts/bump-version-code.sh
  scripts/install_pods.sh
  src/ui/Onboarding/__snapshots__/Onboarding.tests.js.snap
  src/ui/Onboarding/index.js
  yarn.lock
Labels: merge

#16 chore: Sets Production Verson Code
  scripts/bump-version-code.sh
Labels: merge

#15 chore: Adds Pull Request Template
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: merge

#6 chore: Adds Feature Click Analytics
  src/tabs/home/Features/index.js
Labels: merge

#3 chore: (DEV-4307) Adds Analytics to Live Stream Clicks
  src/content-single/MediaControls/index.js
  src/live/LiveButton.js
Labels: merge

#17 chore: Changes Giving Link
  src/tabs/connect/ActionBar.js
Labels: merge

#19 fix: Removed Tracking to Correct Links
  src/live/LiveButton.js
  src/tabs/home/Features/index.js
Labels: merge

#20 Release 7.5.15
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  android/app/build.gradle
  ios/newspringchurchapp-tvOS/Info.plist
  ios/newspringchurchapp-tvOSTests/Info.plist
  ios/newspringchurchapp.xcodeproj/project.pbxproj
  ios/newspringchurchapp/Info.plist
  ios/newspringchurchappTests/Info.plist
  package.json
  schema.graphql
  scripts/bump-version-code.sh
  src/content-single/MediaControls/index.js
  src/live/LiveButton.js
  src/tabs/connect/ActionBar.js
  src/tabs/home/Features/index.js
Labels: ready for review

#21 fix: Fixes saving inconsistencies
  src/prayer/data/queries/getCampusPrayers.js
  src/prayer/data/queries/getGroupPrayers.js
  src/prayer/data/queries/getPrayers.js
Labels: merge

#25 fix: Fix Styling on Connect Tab
  src/tabs/connect/Connect.js
Labels: merge, ready for review

#22 fix: Fixes Analytics mutations
  src/index.js
Labels: merge

#26 chore: Notifies for Bad Content Images
  src/content-single/HTMLContent/index.js
Labels: merge

#24 chore: Adds AppCenter SDK
  android/app/src/main/assets/appcenter-config.json
  android/app/src/main/res/values/strings.xml
  appcenter-post-clone.sh
  ios/AppCenter-Config.plist
  ios/Podfile.lock
  ios/newspringchurchapp.xcodeproj/project.pbxproj
  ios/newspringchurchapp/AppDelegate.m
  package.json
  src/index.js
  yarn.lock
Labels: merge

#27 chore: Automates Versioning
  .travis.yml
Labels: merge

#28 chore: Updates Android version codes
  scripts/bump-version-code.sh
Labels: merge

#30 chore: Adds store to bugsnag reports
  schema.graphql
  src/bugsnag.js
  src/index.js
Labels: merge

#29 release: 7.5.16-Beta
  .travis.yml
  CHANGELOG.md
  android/app/build.gradle
  android/app/src/main/assets/appcenter-config.json
  android/app/src/main/res/values/strings.xml
  appcenter-post-clone.sh
  ios/AppCenter-Config.plist
  ios/Podfile.lock
  ios/newspringchurchapp-tvOS/Info.plist
  ios/newspringchurchapp-tvOSTests/Info.plist
  ios/newspringchurchapp.xcodeproj/project.pbxproj
  ios/newspringchurchapp/AppDelegate.m
  ios/newspringchurchapp/Info.plist
  ios/newspringchurchappTests/Info.plist
  package.json
  schema.graphql
  scripts/bump-version-code.sh
  src/bugsnag.js
  src/content-single/HTMLContent/index.js
  src/index.js
  src/prayer/data/queries/getCampusPrayers.js
  src/prayer/data/queries/getGroupPrayers.js
  src/prayer/data/queries/getPrayers.js
  src/tabs/connect/Connect.js
  yarn.lock
Labels: merge

#31 chore: Adds Stage to ENV file
  .env.production
  src/bugsnag.js
Labels: merge

#34 fix: Fixes auth reset thrashing
  src/NavigationService.js
  src/client/index.js
  src/user-settings/index.js
Labels: merge

#35 Beta Release
  .env.production
  src/NavigationService.js
  src/bugsnag.js
  src/client/index.js
  src/user-settings/index.js
Labels: ready for review

#36 chore: Upgrades to Apollos 1.2.5
  __mocks__/react-native-permissions/index.js
  apollos.json
  ios/Podfile
  ios/Podfile.lock
  package.json
  src/tabs/connect/RecentlyLikedTileFeed/RecentlyLikedTileFeed.js
  src/tabs/connect/getUserProfile.js
  src/tabs/discover/DiscoverFeed/TileContentFeed.js
  src/user-settings/Locations/Marker.js
  src/user-settings/getUserPhoto.js
  src/user-settings/uploadPhoto.js
  yarn.lock
Labels: merge

#32 chore: Update Campaign Card
  src/tabs/home/Home.js
  src/ui/BrandedCard.js
Labels: merge

#41 chore: Beta Release
  __mocks__/react-native-permissions/index.js
  apollos.json
  ios/Podfile
  ios/Podfile.lock
  package.json
  src/tabs/connect/RecentlyLikedTileFeed/RecentlyLikedTileFeed.js
  src/tabs/connect/getUserProfile.js
  src/tabs/discover/DiscoverFeed/TileContentFeed.js
  src/tabs/home/Home.js
  src/ui/BrandedCard.js
  src/user-settings/Locations/Marker.js
  src/user-settings/getUserPhoto.js
  src/user-settings/uploadPhoto.js
  yarn.lock
Labels: ready for review

#40 chore: Adds Github releases
  .travis.yml
  CHANGELOG.md
  package.json
  yarn.lock
Labels: merge

#38 chore: Adds a restart command
  package.json
Labels: merge

#39 chore: Adds Appcenter crash reports
  src/index.js
Labels: merge
